sonar-scanner \
  -Dsonar.projectKey=Group4 \
  -Dsonar.sources= cnn_deployment, NLP, gru_deployment, lstm_deployment, vgg_deployment
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.token=sqp_bdde6d2e345cf0b400766593595c6f56158cf027