sonar.projectKey=Group4
sonar.projectName=Group4
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=squ_a1e2264755e1f32c846336e6f397b462b456a345
sonar.python.coverage.reportPaths=coverage.xml
