/Users/nithish/Downloads/sonar-scanner-7.1.0.4889-linux-x64/bin/sonar-scanner
sonar-scanner \
  -Dsonar.projectKey=Group4 \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.token=sqp_bdde6d2e345cf0b400766593595c6f56158cf027