name: Test Branch CI/CD

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  validate-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check for required files
        working-directory: ./Deployment/CaseStudy1
        run: |
          echo "Checking if app.py and Dockerfile exist..."
          if [[ -f "app.py" && -f "Dockerfile" ]]; then
            echo "Test Passed."
          else
            echo "Test failed due to app.py file and Dockerfile not found."
            exit 1
          }
